import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css',
                'resources/css/theme-invest-app.css',
                'resources/css/theme-drawer-shared.css',
                'resources/css/adminInsert.css',
                'resources/css/adminView.css',
                'resources/css/adminStockManagement.css',
                'resources/css/adminUserManagement.css',
                'resources/css/adminStockInsert.css',
                'resources/css/login.css',
                'resources/css/loginRegister.css',
                'resources/css/userFollow.css',
                'resources/css/footer.css',
                'resources/css/pages/user-home.css',
                'resources/css/pages/user-profile.css',
                'resources/css/pages/user-follow-form.css',
                'resources/css/pages/user-email-settings.css',
                'resources/css/pages/investment-performance.css',
                'resources/css/pages/admin-stock-update.css',
                'resources/css/pages/admin-user-update.css',
                'resources/css/pages/public-profile.css',
                'resources/css/pages/user-buy.css',
                'resources/css/pages/user-sell.css',
                'resources/css/pages/user-follow.css',
                'resources/js/Admin.js',
                'resources/js/AdminStockManagement.js',
                'resources/js/AdminUserManagement.js',
                'resources/js/AdminStockInsert.js',
                'resources/js/AdminStockUpdate.js',
                'resources/js/User.js',
                'resources/js/app.js',
                'resources/js/pages/login.js',
                'resources/js/pages/register.js',
                'resources/js/pages/forgot-password.js',
                'resources/js/pages/user-home.js',
                'resources/js/pages/user-profile.js',
                'resources/js/pages/user-follow-form.js',
                'resources/js/pages/user-email-settings.js',
                'resources/js/pages/investment-performance.js',
                'resources/js/pages/admin-stock-update.js',
                'resources/js/pages/admin-home.js',
                'resources/js/pages/user-follow.js',
                'resources/js/pages/user-buy.js',
                'resources/js/pages/user-sell.js',
                'resources/js/pages/user-change-password.js',
                'resources/js/pages/user-insert-follow.js',
                'resources/js/pages/user-cash-in.js',
                'resources/js/pages/user-cash-out.js',
                'resources/js/pages/user-update-info-profile.js',
                'resources/js/pages/admin-insert.js',
                'resources/js/pages/admin-stock-management.js',
                'resources/js/pages/admin-user-management.js',
                'resources/js/pages/admin-upload-file.js',
                'resources/js/pages/admin-update-risk.js',
                'resources/js/pages/reset-password.js',
                'resources/js/pages/show-risk-level.js'],
            refresh: true,
        }),
    ],
    
});
